import apiClient from './apiClient';
import {
  ApiResponse,
  ITask,
  CreateTaskDTO,
  UpdateTaskDTO,
  BulkUpdateTasksDTO,
  IProject,
  CreateProjectDTO,
  UpdateProjectDTO,
  INote,
  CreateNoteDTO,
  UpdateNoteDTO,
  IJobApplication,
  CreateJobDTO,
  UpdateJobDTO,
  IExpense,
  CreateExpenseDTO,
  UpdateExpenseDTO,
  IJournalEntry,
  CreateJournalDTO,
  UpdateJournalDTO,
  IHabit,
  CreateHabitDTO,
  UpdateHabitDTO,
  IFlashcard,
  CreateFlashcardDTO,
  UpdateFlashcardDTO,
  GenerateAiFlashcardDTO,
  IStudySession,
  CreateStudySessionDTO,
  UpdateStudySessionDTO,
  IResume,
  CreateResumeDTO,
  UpdateResumeDTO,
  IDsaProblem,
  CreateDsaDTO,
  UpdateDsaDTO,
  IUser,
  UpdateProfileDTO,
} from '@lifeos/contracts';

export const apiSdk = {
  tasks: {
    getAll: async () => (await apiClient.get<ApiResponse<ITask[]>>('/tasks')).data.data,
    create: async (dto: CreateTaskDTO) => (await apiClient.post<ApiResponse<ITask>>('/tasks', dto)).data.data,
    update: async (id: string, dto: UpdateTaskDTO) => (await apiClient.put<ApiResponse<ITask>>(`/tasks/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/tasks/${id}`)).data.data,
    bulkUpdate: async (dto: BulkUpdateTasksDTO) => (await apiClient.put<ApiResponse<ITask[]>>('/tasks/bulk', dto)).data.data,
  },
  projects: {
    getAll: async () => (await apiClient.get<ApiResponse<IProject[]>>('/projects')).data.data,
    create: async (dto: CreateProjectDTO) => (await apiClient.post<ApiResponse<IProject>>('/projects', dto)).data.data,
    update: async (id: string, dto: UpdateProjectDTO) => (await apiClient.put<ApiResponse<IProject>>(`/projects/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/projects/${id}`)).data.data,
  },
  notes: {
    getAll: async () => (await apiClient.get<ApiResponse<INote[]>>('/notes')).data.data,
    create: async (dto: CreateNoteDTO) => (await apiClient.post<ApiResponse<INote>>('/notes', dto)).data.data,
    update: async (id: string, dto: UpdateNoteDTO) => (await apiClient.put<ApiResponse<INote>>(`/notes/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/notes/${id}`)).data.data,
  },
  jobs: {
    getAll: async () => (await apiClient.get<ApiResponse<IJobApplication[]>>('/jobs')).data.data,
    create: async (dto: CreateJobDTO) => (await apiClient.post<ApiResponse<IJobApplication>>('/jobs', dto)).data.data,
    update: async (id: string, dto: UpdateJobDTO) => (await apiClient.put<ApiResponse<IJobApplication>>(`/jobs/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/jobs/${id}`)).data.data,
  },
  expenses: {
    getAll: async () => (await apiClient.get<ApiResponse<IExpense[]>>('/expenses')).data.data,
    create: async (dto: CreateExpenseDTO) => (await apiClient.post<ApiResponse<IExpense>>('/expenses', dto)).data.data,
    update: async (id: string, dto: UpdateExpenseDTO) => (await apiClient.put<ApiResponse<IExpense>>(`/expenses/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/expenses/${id}`)).data.data,
  },
  journals: {
    getAll: async () => (await apiClient.get<ApiResponse<IJournalEntry[]>>('/journals')).data.data,
    create: async (dto: CreateJournalDTO) => (await apiClient.post<ApiResponse<IJournalEntry>>('/journals', dto)).data.data,
    update: async (id: string, dto: UpdateJournalDTO) => (await apiClient.put<ApiResponse<IJournalEntry>>(`/journals/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/journals/${id}`)).data.data,
  },
  habits: {
    getAll: async () => (await apiClient.get<ApiResponse<IHabit[]>>('/habits')).data.data,
    create: async (dto: CreateHabitDTO) => (await apiClient.post<ApiResponse<IHabit>>('/habits', dto)).data.data,
    update: async (id: string, dto: UpdateHabitDTO) => (await apiClient.put<ApiResponse<IHabit>>(`/habits/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/habits/${id}`)).data.data,
  },
  flashcards: {
    getAll: async () => (await apiClient.get<ApiResponse<IFlashcard[]>>('/flashcards')).data.data,
    create: async (dto: CreateFlashcardDTO) => (await apiClient.post<ApiResponse<IFlashcard>>('/flashcards', dto)).data.data,
    update: async (id: string, dto: UpdateFlashcardDTO) => (await apiClient.put<ApiResponse<IFlashcard>>(`/flashcards/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/flashcards/${id}`)).data.data,
    generateAi: async (dto: GenerateAiFlashcardDTO) => (await apiClient.post<ApiResponse<IFlashcard[]>>('/flashcards/generate-ai', dto)).data.data,
  },
  study: {
    getAll: async () => (await apiClient.get<ApiResponse<IStudySession[]>>('/study')).data.data,
    create: async (dto: CreateStudySessionDTO) => (await apiClient.post<ApiResponse<IStudySession>>('/study', dto)).data.data,
    update: async (id: string, dto: UpdateStudySessionDTO) => (await apiClient.put<ApiResponse<IStudySession>>(`/study/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/study/${id}`)).data.data,
  },
  resumes: {
    getAll: async () => (await apiClient.get<ApiResponse<IResume[]>>('/resumes')).data.data,
    create: async (dto: CreateResumeDTO) => (await apiClient.post<ApiResponse<IResume>>('/resumes', dto)).data.data,
    update: async (id: string, dto: UpdateResumeDTO) => (await apiClient.put<ApiResponse<IResume>>(`/resumes/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/resumes/${id}`)).data.data,
  },
  dsa: {
    getAll: async () => (await apiClient.get<ApiResponse<IDsaProblem[]>>('/dsa')).data.data,
    create: async (dto: CreateDsaDTO) => (await apiClient.post<ApiResponse<IDsaProblem>>('/dsa', dto)).data.data,
    update: async (id: string, dto: UpdateDsaDTO) => (await apiClient.put<ApiResponse<IDsaProblem>>(`/dsa/${id}`, dto)).data.data,
    delete: async (id: string) => (await apiClient.delete<ApiResponse<{ id: string }>>(`/dsa/${id}`)).data.data,
  },
  user: {
    getProfile: async () => (await apiClient.get<ApiResponse<IUser>>('/users/me')).data.data,
    updateProfile: async (dto: UpdateProfileDTO) => (await apiClient.put<ApiResponse<IUser>>('/users/me', dto)).data.data,
  },
  dashboard: {
    getSummary: async () => (await apiClient.get<ApiResponse<any>>('/dashboard/summary')).data.data,
    getHeatmap: async () => (await apiClient.get<ApiResponse<{ activities: { date: string; count: number; level?: number }[] }>>('/dashboard/heatmap')).data.data,
  },
  notifications: {
    getAll: async () => (await apiClient.get<ApiResponse<any[]>>('/notifications')).data.data,
    markAllRead: async (notificationIds?: string[]) => (await apiClient.post<ApiResponse<any>>('/notifications/mark-read', { notificationIds })).data.data,
  },
};
